services:
  - type: web
    name: dandhrecipes
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python3 manage.py migrate --noinput
      python3 manage.py collectstatic --noinput
    startCommand: gunicorn recipes.wsgi:application --bind 0.0.0.0:$PORT --workers=4
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        fromDatabase:
          name: tandoordb
          property: database
      - key: DB_USER
        fromDatabase:
          name: tandoordb
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tandoordb
          property: password
      - key: DB_HOST
        fromDatabase:
          name: tandoordb
          property: host
      - key: DB_PORT
        fromDatabase:
          name: tandoordb
          property: port

databases:
  - name: tandoordb
    plan: free
